# Generated by Django 4.1.2 on 2022-10-21 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sica.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clase',
                'ordering': ['id_clase'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cuenta',
                'ordering': ['id_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.clase', verbose_name='Clase')),
            ],
            options={
                'db_table': 'grupo',
                'ordering': ['id_grupo'],
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id_subCuenta', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre_subCuenta', models.CharField(max_length=50)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'db_table': 'subCuenta',
                'ordering': ['id_subCuenta'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipoTransaccion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TipoTransaccion',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_transaccionT', models.CharField(max_length=50, null=True)),
                ('fecha_transaccionT', models.DateField(help_text='Consejo: <em>Presione en el calendario</em>.', validators=[sica.models.validar_fecha], verbose_name='Fecha de Transaccion')),
                ('monto', models.FloatField()),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.clase', verbose_name='Clase')),
                ('id_cuenta', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_grupo', chained_model_field='id_grupo', on_delete=django.db.models.deletion.PROTECT, to='sica.cuenta', verbose_name='Cuenta')),
                ('id_grupo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_clase', chained_model_field='id_clase', on_delete=django.db.models.deletion.PROTECT, to='sica.grupo', verbose_name='Grupo')),
                ('id_subCuenta', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_cuenta', chained_model_field='id_cuenta', on_delete=django.db.models.deletion.PROTECT, to='sica.subcuenta', verbose_name='SubCuenta')),
                ('id_tipoTransaccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.tipotransaccion', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tipo de Transacción')),
            ],
            options={
                'db_table': 'transaccion',
                'ordering': ['id_transaccion'],
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.grupo', verbose_name='Grupo'),
        ),
    ]
