# Generated by Django 4.1.2 on 2022-10-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.IntegerField(primary_key=True, serialize=False, verbose_name='N° de partida')),
                ('descripcion_partida', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'partidas',
                'ordering': ['id_partida'],
            },
        ),
    ]
