# Generated by Django 4.1.2 on 2022-10-23 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.IntegerField(primary_key=True, serialize=False, verbose_name='N° de partida')),
                ('descripcion_partida', models.CharField(max_length=50, null=True, verbose_name='Descripcion')),
            ],
            options={
                'db_table': 'partidas',
                'ordering': ['id_partida'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Producto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio_Producto', models.FloatField(verbose_name='Precio')),
            ],
            options={
                'db_table': 'Producto',
                'ordering': ['id_Producto'],
            },
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion_transaccionT',
            field=models.CharField(max_length=80, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.clase', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_subCuenta',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_cuenta', chained_model_field='id_cuenta', on_delete=django.db.models.deletion.PROTECT, to='sica.subcuenta', verbose_name='Sub-Cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_tipoTransaccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.tipotransaccion', verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='OrdendeProduccion',
            fields=[
                ('id_OrdendeProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_cliente', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fecha_Actual', models.DateField(help_text='Consejo: <em>Presione en el calendario</em>.', verbose_name='Fecha de Compra')),
                ('numero_Pedido', models.IntegerField(null=True, verbose_name='N° de Pedido ')),
                ('cantidad_Producto', models.IntegerField(null=True, verbose_name='Cantidad de Producto')),
                ('detalles_Pedido', models.CharField(max_length=50, verbose_name='Observaciones')),
                ('producto_Orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.producto', verbose_name='Lista de Productos')),
            ],
            options={
                'db_table': 'ordedeProduccion',
                'ordering': ['id_OrdendeProduccion'],
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sica.partida'),
            preserve_default=False,
        ),
    ]
