# Generated by Django 4.1.2 on 2022-10-24 03:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0002_partida_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManodeObra',
            fields=[
                ('id_manodeObra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_manodeObra', models.DateField(help_text='Consejo: <em>Presione en el calendario</em>.', verbose_name='Fecha')),
                ('horas_manodeObra', models.IntegerField(verbose_name='Horas')),
                ('salario_manodeObra', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario por Hora')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_OrdendeProduccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.ordendeproduccion')),
            ],
            options={
                'db_table': 'ManodeObra',
                'ordering': ['id_OrdendeProduccion'],
            },
        ),
    ]
