# Generated by Django 4.1.2 on 2022-10-22 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0003_transaccion_id_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion_transaccionT',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.clase', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_subCuenta',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_cuenta', chained_model_field='id_cuenta', on_delete=django.db.models.deletion.PROTECT, to='sica.subcuenta', verbose_name='Sub-Cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_tipoTransaccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.tipotransaccion', verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
