# Generated by Django 4.1.2 on 2022-10-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0004_alter_transaccion_descripcion_transacciont_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion_transaccionT',
            field=models.CharField(max_length=80, null=True, verbose_name='Descripcion'),
        ),
    ]
