# Generated by Django 4.1.2 on 2022-10-22 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0005_alter_transaccion_descripcion_transacciont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
