# Generated by Django 4.1.2 on 2022-10-23 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sica", "0007_alter_transaccion_monto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaccion",
            name="monto",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
