# Generated by Django 4.1.2 on 2022-10-24 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0007_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcuenta',
            name='saldo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
