# Generated by Django 4.1.2 on 2022-10-24 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0008_subcuenta_saldo_alter_transaccion_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcuenta',
            old_name='saldo',
            new_name='debe',
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='haber',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
