# Generated by Django 4.1.2 on 2022-10-24 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0009_rename_saldo_subcuenta_debe_subcuenta_haber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id_ajuste', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ajuste', models.DateField(auto_now_add=True)),
                ('descripcion_ajuste', models.CharField(max_length=80, null=True, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_clase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.clase', verbose_name='Clase')),
                ('id_cuenta', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_grupo', chained_model_field='id_grupo', on_delete=django.db.models.deletion.PROTECT, to='sica.cuenta', verbose_name='Cuenta')),
                ('id_grupo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_clase', chained_model_field='id_clase', on_delete=django.db.models.deletion.PROTECT, to='sica.grupo', verbose_name='Grupo')),
                ('id_subCuenta', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_cuenta', chained_model_field='id_cuenta', on_delete=django.db.models.deletion.PROTECT, to='sica.subcuenta', verbose_name='Sub-Cuenta')),
                ('id_tipoTransaccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sica.tipotransaccion', verbose_name='Tipo de Transacción')),
            ],
            options={
                'db_table': 'ajuste',
                'ordering': ['id_ajuste'],
            },
        ),
    ]
